#! /bin/sh

# Create PDF of the Olive source code.
#	olivesrc-enscript.pdf	created using enscript

# Ignore "WebContent/scripts/jquery-ui-1.8.6.custom/"
# because it's huge and we're not using it.
# But here is the syntax for it, with the exception of "WebContent/scripts/jquery-ui-1.8.6.custom/development-bundle":
#    WebContent/scripts/jquery-ui-1.8.6.custom/css/ui-lightness/images/ui-bg_diagonals-thick_18_b81900_40x40.png \
#    WebContent/scripts/jquery-ui-1.8.6.custom/css/ui-lightness/images/ui-bg_diagonals-thick_20_666666_40x40.png \
#    WebContent/scripts/jquery-ui-1.8.6.custom/css/ui-lightness/images/ui-bg_flat_10_000000_40x100.png \
#    WebContent/scripts/jquery-ui-1.8.6.custom/css/ui-lightness/images/ui-bg_glass_100_f6f6f6_1x400.png \
#    WebContent/scripts/jquery-ui-1.8.6.custom/css/ui-lightness/images/ui-bg_glass_100_fdf5ce_1x400.png \
#    WebContent/scripts/jquery-ui-1.8.6.custom/css/ui-lightness/images/ui-bg_glass_65_ffffff_1x400.png \
#    WebContent/scripts/jquery-ui-1.8.6.custom/css/ui-lightness/images/ui-bg_gloss-wave_35_f6a828_500x100.png \
#    WebContent/scripts/jquery-ui-1.8.6.custom/css/ui-lightness/images/ui-bg_highlight-soft_100_eeeeee_1x100.png \
#    WebContent/scripts/jquery-ui-1.8.6.custom/css/ui-lightness/images/ui-bg_highlight-soft_75_ffe45c_1x100.png \
#    WebContent/scripts/jquery-ui-1.8.6.custom/css/ui-lightness/images/ui-icons_222222_256x240.png \
#    WebContent/scripts/jquery-ui-1.8.6.custom/css/ui-lightness/images/ui-icons_228ef1_256x240.png \
#    WebContent/scripts/jquery-ui-1.8.6.custom/css/ui-lightness/images/ui-icons_ef8c08_256x240.png \
#    WebContent/scripts/jquery-ui-1.8.6.custom/css/ui-lightness/images/ui-icons_ffd27a_256x240.png \
#    WebContent/scripts/jquery-ui-1.8.6.custom/css/ui-lightness/images/ui-icons_ffffff_256x240.png \
#    WebContent/scripts/jquery-ui-1.8.6.custom/css/ui-lightness/jquery-ui-1.8.6.custom.css \
#    WebContent/scripts/jquery-ui-1.8.6.custom/js/jquery-1.4.2.min.js \
#    WebContent/scripts/jquery-ui-1.8.6.custom/js/jquery-ui-1.8.6.custom.min.js \
#    WebContent/scripts/jquery-ui-1.8.6.custom/index.html
#    WebContent/scripts/jquery-1.4.4.js \
#    WebContent/scripts/jquery.1.4.4.min.js \


# List of files to be included in PDF.
FILES="\
    README \
    .classpath \
    .project \
    .settings/.jsdtscope \
    .settings/org.eclipse.jdt.core.prefs \
    .settings/org.eclipse.wst.common.component \
    .settings/org.eclipse.wst.common.project.facet.core.xml \
    .settings/org.eclipse.wst.jsdt.ui.superType.container \
    .settings/org.eclipse.wst.jsdt.ui.superType.name \
    \
    WebContent/META-INF/MANIFEST.MF \
    WebContent/META-INF/context.xml \
        \
    WebContent/WEB-INF/sun-web.xml \
    WebContent/WEB-INF/web.xml \
        \
    WebContent/css/reset.css \
    WebContent/css/style.css \
        \
    WebContent/doc/favicon_notes.txt \
        \
    WebContent/scripts/google-analytics.js \
    WebContent/scripts/script.js \
        \
    WebContent/account.jsp \
    WebContent/editor.jsp \
    WebContent/index.jsp \
    WebContent/projects.jsp \
    WebContent/test.jsp \
    \
    src/com/readytalk/olive/logic/OliveLogic.java \
    src/com/readytalk/olive/model/Project.java \
    src/com/readytalk/olive/model/User.java \
    src/com/readytalk/olive/servlet/OliveServlet.java \
    "

# Remove any old PostScript or PDF versions lying around.
rm -f olivesrc-enscript.ps olivesrc-enscript.pdf

# Generate PostScript versions of each file, appending them to a single
# PostScript file for each of a2ps and enscript versions.
for f in ${FILES}
do
    enscript -2Gr -T4 -bOlive -p- ${f} >> olivesrc-enscript.ps
done

# Convert the enscript version from PostScript to PDF, removing the PostScript
# version when completed.
ps2pdf olivesrc-enscript.ps olivesrc-enscript.pdf
rm -f olivesrc-enscript.ps
