#! /bin/sh

# Create PDF of the Olive source code. Ignore third-party code.
#    olivesrc.pdf    created using enscript

# List of files to be included in PDF.
FILES="\
    README \
    OliveData.dmp \
    \
    src/com/readytalk/olive/json/AddToSelectedRequest.java \
    src/com/readytalk/olive/json/CombineVideosRequest.java \
    src/com/readytalk/olive/json/DeleteAccountRequest.java \
    src/com/readytalk/olive/json/DeleteProjectRequest.java \
    src/com/readytalk/olive/json/DeleteVideoRequest.java \
    src/com/readytalk/olive/json/GeneralRequest.java \
    src/com/readytalk/olive/json/GetAccountInformationResponse.java \
    src/com/readytalk/olive/json/RemoveFromSelectedRequest.java \
    src/com/readytalk/olive/json/RenameProjectRequest.java \
    src/com/readytalk/olive/json/RenameVideoRequest.java \
    src/com/readytalk/olive/json/SplitVideoRequest.java \
    src/com/readytalk/olive/json/UpdateProjectsPositionRequest.java \
    src/com/readytalk/olive/json/UpdateTimelinePositionRequest.java \
    src/com/readytalk/olive/json/UpdateVideosPositionRequest.java \
    src/com/readytalk/olive/json/ZencoderInitialResponse.java \
    \
    src/com/readytalk/olive/logic/DatabaseApi.java \
    src/com/readytalk/olive/logic/S3Api.java \
    src/com/readytalk/olive/logic/Security.java \
    src/com/readytalk/olive/logic/ZencoderApi.java \
    \
    src/com/readytalk/olive/model/Project.java \
    src/com/readytalk/olive/model/User.java \
    src/com/readytalk/olive/model/Video.java \
    \
    src/com/readytalk/olive/servlet/OliveServlet.java \
    \
    src/com/readytalk/olive/util/Attribute.java \
    src/com/readytalk/olive/util/InvalidFileSizeException.java \
    \
    WebContent/css/account.css \
    WebContent/css/editor.css \
    WebContent/css/index.css \
    WebContent/css/master.css \
    WebContent/css/projects.css \
    WebContent/css/reset.css \
        \
    WebContent/META-INF/context.xml \
        \
    WebContent/temp/maintainer.txt \
        \
    WebContent/scripts/account.js \
    WebContent/scripts/editor.js \
    WebContent/scripts/index.js \
    WebContent/scripts/master.js \
    WebContent/scripts/projects.js \
        \
    WebContent/WEB-INF/sun-web.xml \
    WebContent/WEB-INF/web.xml \
        \
    WebContent/account.jsp \
    WebContent/editor.jsp \
    WebContent/footer.jsp \
    WebContent/forgot.jsp \
    WebContent/header.jsp \
    WebContent/index.jsp \
    WebContent/logout.jsp \
    WebContent/new-password-form.jsp \
    WebContent/projects.jsp \
    "

# Remove any old PostScript or PDF versions lying around.
rm -f olivesrc.ps olivesrc.pdf

# Generate PostScript versions of each file, appending them to a single
# PostScript file for the enscript version.
for f in ${FILES}
do
    enscript -2Gr -T4 -bOlive -p- ${f} >> olivesrc.ps
done

# Convert the enscript version from PostScript to PDF, removing the PostScript
# version when completed.
ps2pdf olivesrc.ps olivesrc.pdf
rm -f olivesrc.ps
