package com.readytalk.olive.util;

public enum Attribute {
	IS_AUTHORIZED, USERNAME, PASSWORD, EDIT_SUCCESSFULLY, ADD_SUCCESSFULLY, PROJECT_NAME, PASSWORDS_MATCH, IS_SAFE, EMAIL, NAME, SECURITY_QUESTION, SECURITY_ANSWER, IS_CORRECT
}
